# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171112_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='result_bet_type',
            field=models.CharField(blank=True, choices=[('Differenz', 'differenz'), ('Niete', 'niete'), ('Remis Tendenz', 'remis_tendenz'), ('Tendenz', 'tendenz'), ('Volltreffer', 'volltreffer')], max_length=50, null=True),
        ),
    ]
