# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180124_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('hometeam', 'awayteam', 'round')]),
        ),
    ]
