# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180124_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
