# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180511_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='force_mail',
            new_name='force_all_users',
        ),
    ]
