# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180520_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='force_active_users',
            field=models.BooleanField(default=False),
        ),
    ]
