# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_post_force_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='force_inactive_users',
            field=models.BooleanField(default=False),
        ),
    ]
