# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_game_openligadb_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='openligadb_match_id',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
