# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


# TODO P2 set correct IDs manually in this data migration
def set_ids(apps, schema_editor):
    # We can't import the Game model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Game = apps.get_model('main', 'Game')

    for person in Game.objects.all():
        person.name = '%s %s' % (person.first_name, person.last_name)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180607_2323.py'),
    ]

    operations = [
        migrations.RunPython(set_ids),
    ]
